
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kunal
 */
public class LodingScreenTicketShow extends javax.swing.JFrame {

    /**
     * Creates new form LodingScreenTicketShow
     */
    void splashScreen(){
        try {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(100);
                labelco.setText(i+" %");
               
                if(i<10)
                {
                    Thread.sleep(200);
                    labellodingditails.setText("Loding ...");
                }
                    
                else if(i<40)
                {
                     Thread.sleep(30);
                    labellodingditails.setText("Loding Modules ...");    
                }
                    
                else if(i<60){
                     Thread.sleep(500);
                    labellodingditails.setText("Connecting Database ...");
                }
                   
                if(i==100){
                    dispose();
                  new loginTicketFrame().show();
                }
                     
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public LodingScreenTicketShow() {
        setUndecorated(true);
        initComponents();
        
        // Scalling Images For Main Screen 
        ImageIcon li = new ImageIcon(getClass().getResource("/Images/img1.png"));
        ImageIcon li2 = new ImageIcon(getClass().getResource("/Images/mainimg.jpg"));
        Image image2 = (li2).getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
        Image image = (li).getImage().getScaledInstance(labelgif.getWidth(), labelgif.getHeight(),Image.SCALE_SMOOTH);
        li2 = new ImageIcon(image2);
        li = new ImageIcon(image);
        jLabel1.setIcon(li2);
        labelgif.setIcon(li);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmainScreen = new javax.swing.JPanel();
        labelco = new javax.swing.JLabel();
        labelgif1 = new javax.swing.JLabel();
        labelgif = new javax.swing.JLabel();
        labellodingditails = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelmainScreen.setBackground(new java.awt.Color(0, 0, 0));
        panelmainScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelco.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        labelco.setForeground(new java.awt.Color(255, 255, 255));
        labelco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelco.setText("0%");
        panelmainScreen.add(labelco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 120, 70));

        labelgif1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Spin.gif"))); // NOI18N
        labelgif1.setText("jLabel2");
        panelmainScreen.add(labelgif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 190, 250));

        labelgif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelgif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img1.png"))); // NOI18N
        panelmainScreen.add(labelgif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 650, 620));

        labellodingditails.setFont(new java.awt.Font("Viner Hand ITC", 2, 24)); // NOI18N
        labellodingditails.setForeground(new java.awt.Color(255, 255, 255));
        labellodingditails.setText("Started...");
        panelmainScreen.add(labellodingditails, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 340, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainimg.jpg"))); // NOI18N
        panelmainScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmainScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LodingScreenTicketShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LodingScreenTicketShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LodingScreenTicketShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LodingScreenTicketShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        LodingScreenTicketShow ticket = new LodingScreenTicketShow();
        ticket.setVisible(true);
        ticket.splashScreen();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelco;
    private javax.swing.JLabel labelgif;
    private javax.swing.JLabel labelgif1;
    private javax.swing.JLabel labellodingditails;
    private javax.swing.JPanel panelmainScreen;
    // End of variables declaration//GEN-END:variables
}
