import java.sql.*;
import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;

public class loginTicketFrame extends javax.swing.JFrame {

    String user_id,password;
    public loginTicketFrame() {
        initComponents();
        setLocationRelativeTo(null);
      
    }
    void dataasefunction(){
        //For Create  Table In Table In The dataBase 
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_show","root","");
            Statement stmt = con.createStatement();
            String quiry = "CREATE TABLE usersnew("
                    +"id INT NOT NULL AUTO_INCREAMENT,"
                    +"name  VARCHSR(50) NOT NULL,"
                    +"password VARCHAR(50) NOT NULL,"
                    +"PRIMARY KEY(id)";
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
         
         // For The 
    }
    void insertData()
    {
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_show","root","");
            Statement stmt = con.createStatement();
            String input = "INSERT INTO `users_logins`( `user_id`, `password`) VALUES ('"+login_id_TextField.getText()+"','"+password_jPasswordField1.getText()+"')" ;
            stmt.execute(input);
            System.out.println("upDated...");
            con.close();
            dispose();
            
         }
         catch(Exception e){
             System.out.println(e);
             
         }
    }
    void login()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/book_my_show","root","");
            Statement stmt = con.createStatement();
            String sql = "Select * from users_logins where  user_id = '"+login_id_TextField.getText()+"'and password='"+password_jPasswordField1.getText().toString()+"'";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                 JOptionPane.showMessageDialog(null,"login SucessFully...");
                 dispose();
            }              
            else
                JOptionPane.showMessageDialog(null,"Invalid Information...");
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    void getData()
    {
          user_id=login_id_TextField.getText();
          password=password_jPasswordField1.getText();
    }
  
   boolean loginData()
    {
        if(user_id.equals("Kunal@2552")&&password.equals("kunal@2552"))  
        {
            JOptionPane.showMessageDialog(null,"Login Sucessfully"); 
            new mainTicketBookFrame().show();
            return true;
        }       
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        password_jLabel = new javax.swing.JLabel();
        password_jPasswordField1 = new javax.swing.JPasswordField();
        login_id_TextField = new javax.swing.JTextField();
        id_jLabel1 = new javax.swing.JLabel();
        cancel_jButton1 = new javax.swing.JButton();
        login_jButton2 = new javax.swing.JButton();
        login_jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login Frame");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password_jLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        password_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        password_jLabel.setText("login Id                 :-");
        jPanel1.add(password_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        password_jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(password_jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 119, 284, 39));

        login_id_TextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(login_id_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 33, 284, 37));

        id_jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        id_jLabel1.setText("password             :-");
        jPanel1.add(id_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 126, -1, -1));

        cancel_jButton1.setBackground(new java.awt.Color(0, 0, 0));
        cancel_jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel_jButton1.setForeground(new java.awt.Color(255, 255, 255));
        cancel_jButton1.setText("cancel");
        cancel_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 215, 125, 36));

        login_jButton2.setBackground(new java.awt.Color(0, 0, 0));
        login_jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_jButton2.setForeground(new java.awt.Color(255, 255, 255));
        login_jButton2.setText("Login");
        login_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(login_jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 125, 36));

        login_jButton3.setBackground(new java.awt.Color(0, 0, 0));
        login_jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_jButton3.setForeground(new java.awt.Color(255, 255, 255));
        login_jButton3.setText("UpDate");
        login_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(login_jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 125, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancel_jButton1ActionPerformed

    private void login_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jButton2ActionPerformed
        // TODO add your handling code here:      
        //getData();
       /* if(loginData()==false)
            JOptionPane.showMessageDialog(null,"Invalide Infomation"); 
        else                 
            dispose();    */
       login();
    }//GEN-LAST:event_login_jButton2ActionPerformed

    private void login_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jButton3ActionPerformed
        // TODO add your handling code here:
        insertData();
    }//GEN-LAST:event_login_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginTicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_jButton1;
    private javax.swing.JLabel id_jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login_id_TextField;
    private javax.swing.JButton login_jButton2;
    private javax.swing.JButton login_jButton3;
    private javax.swing.JLabel password_jLabel;
    private javax.swing.JPasswordField password_jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
